name: Translate PDFs and Upload to Doc Directory

on:
  push:
    paths:
      - 'pdfs.txt'
  workflow_dispatch:

jobs:
  translate-pdfs:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to access pdfs.txt
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Install required packages and dependencies
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip wget curl

    # Install PDFMathTranslate
    - name: Install PDFMathTranslate
      run: |
        pip install pdf2zh

    # Download PDFs from urls in pdfs.txt
    - name: Download PDFs
      run: |
        mkdir -p pdfs
        while IFS= read -r url; do
          # 提取 URL 的 basename
          filename=$(basename "$url")
          # 检查文件名是否已经包含 .pdf 后缀
          if [[ "$filename" != *.pdf ]]; then
            filename="${filename}.pdf"
          fi
          # 下载文件到指定目录
          wget -O "pdfs/$filename" "$url"          
        done < pdfs.txt

    # Translate PDFs using PDFMathTranslate
    - name: Translate PDFs
      run: |
        mkdir -p translated_pdfs      
        pdf2zh -li en -lo zh --dir pdfs -o translated_pdfs -p 1

    # Move translated PDFs to doc directory
    - name: Prepare to Upload
      run: |
        mkdir -p doc
        mv translated_pdfs/*.* doc/
        ls doc/*.* -a

    # Commit and Push Translated PDFs using github-actions-x/commit
    - name: Commit and Push Translated PDFs
      uses: github-actions-x/commit@v2.9
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Add translated PDFs"
        files: |
          doc/*.pdf
        rebase: 'true'
        name: ${{ env.GITHUB_USER_NAME }}
        email: ${{ env.GITHUB_USER_EMAIL }}
